In [1]:
# Importing dependencies
import pandas as pd
import numpy as np

# Loading the driver stats dataset into a DataFrame
data = pd.read_parquet("driver_stats/data/driver_stats_with_string.parquet")

# Sorting the rows by event timestamps, from oldest to newest
data = data.sort_values(by="event_timestamp")

In [2]:
# Getting the oldest and newest event timestamps from the data
print(f"Earliest event timestamp is {data['event_timestamp'].min()}")
print(f"Latest event timestamp is {data['event_timestamp'].max()}")

Earliest event timestamp is 2021-04-12 07:00:00+00:00
Latest event timestamp is 2021-09-15 17:00:00+00:00

In [3]:
# Inspecting the first 50 feature rows
data.head(50)

,event_timestamp,driver_id,conv_rate,acc_rate,avg_daily_trips,created,string_feature
1082,2021-04-12 07:00:00+00:00,1003,0.186658,0.245490,971,2021-09-15 18:01:55.403,test
721,2021-04-12 07:00:00+00:00,1004,0.891017,0.118256,154,2021-09-15 18:01:55.403,test
1443,2021-04-12 07:00:00+00:00,1002,0.775499,0.947109,890,2021-09-15 18:01:55.403,test
360,2021-04-12 07:00:00+00:00,1005,0.138263,0.955520,553,2021-09-15 18:01:55.403,test
1804,2021-04-12 07:00:00+00:00,1001,0.701558,0.195824,566,2021-09-15 18:01:55.403,test
722,2021-08-31 18:00:00+00:00,1003,0.494782,0.000316,634,2021-09-15 18:01:55.403,test
1444,2021-08-31 18:00:00+00:00,1001,0.910018,0.580611,666,2021-09-15 18:01:55.403,test
1083,2021-08-31 18:00:00+00:00,1002,0.381206,0.347303,268,2021-09-15 18:01:55.403,test
361,2021-08-31 18:00:00+00:00,1004,0.527224,0.893340,963,2021-09-15 18:01:55.403,test
0,2021-08-31 18:00:00+00:00,1005,0.362754,0.697629,31,2021-09-15 18:01:55.403,test
1445,2021-08-31 19:00:00+00:00,1001,0.037472,0.447685,786,2021-09-15 18:01:55.403,test
723,2021-08-31 19:00:00+00:00,1003,0.635551,0.669229,186,2021-09-15 18:01:55.403,test
1,2021-08-31 19:00:00+00:00,1005,0.790768,0.821253,520,2021-09-15 18:01:55.403,test
362,2021-08-31 19:00:00+00:00,1004,0.639311,0.828869,888,2021-09-15 18:01:55.403,test
1084,2021-08-31 19:00:00+00:00,1002,0.082020,0.250333,824,2021-09-15 18:01:55.403,test
1085,2021-08-31 20:00:00+00:00,1002,0.859787,0.494235,688,2021-09-15 18:01:55.403,test
724,2021-08-31 20:00:00+00:00,1003,0.935348,0.221686,129,2021-09-15 18:01:55.403,test
2,2021-08-31 20:00:00+00:00,1005,0.416623,0.939601,777,2021-09-15 18:01:55.403,test
363,2021-08-31 20:00:00+00:00,1004,0.352107,0.222272,677,2021-09-15 18:01:55.403,test
1446,2021-08-31 20:00:00+00:00,1001,0.504876,0.696549,807,2021-09-15 18:01:55.403,test
725,2021-08-31 21:00:00+00:00,1003,0.040856,0.026880,699,2021-09-15 18:01:55.403,test
3,2021-08-31 21:00:00+00:00,1005,0.108623,0.818718,750,2021-09-15 18:01:55.403,test
364,2021-08-31 21:00:00+00:00,1004,0.194456,0.675840,122,2021-09-15 18:01:55.403,test
1086,2021-08-31 21:00:00+00:00,1002,0.689625,0.350684,507,2021-09-15 18:01:55.403,test
1447,2021-08-31 21:00:00+00:00,1001,0.662374,0.117641,493,2021-09-15 18:01:55.403,test
365,2021-08-31 22:00:00+00:00,1004,0.747055,0.253207,750,2021-09-15 18:01:55.403,test
1087,2021-08-31 22:00:00+00:00,1002,0.344545,0.836074,321,2021-09-15 18:01:55.403,test
1448,2021-08-31 22:00:00+00:00,1001,0.321247,0.287713,821,2021-09-15 18:01:55.403,test
4,2021-08-31 22:00:00+00:00,1005,0.244842,0.511777,954,2021-09-15 18:01:55.403,test
726,2021-08-31 22:00:00+00:00,1003,0.869323,0.397098,53,2021-09-15 18:01:55.403,test
1088,2021-08-31 23:00:00+00:00,1002,0.420972,0.913954,402,2021-09-15 18:01:55.403,test
727,2021-08-31 23:00:00+00:00,1003,0.589769,0.064091,636,2021-09-15 18:01:55.403,test
1449,2021-08-31 23:00:00+00:00,1001,0.179109,0.837622,833,2021-09-15 18:01:55.403,test
366,2021-08-31 23:00:00+00:00,1004,0.026817,0.889971,45,2021-09-15 18:01:55.403,test
5,2021-08-31 23:00:00+00:00,1005,0.795372,0.688130,194,2021-09-15 18:01:55.403,test
1450,2021-09-01 00:00:00+00:00,1001,0.320252,0.467902,102,2021-09-15 18:01:55.403,test
367,2021-09-01 00:00:00+00:00,1004,0.786329,0.207808,921,2021-09-15 18:01:55.403,test
728,2021-09-01 00:00:00+00:00,1003,0.249291,0.397794,322,2021-09-15 18:01:55.403,test
6,2021-09-01 00:00:00+00:00,1005,0.065470,0.040953,233,2021-09-15 18:01:55.403,test
1089,2021-09-01 00:00:00+00:00,1002,0.804684,0.568813,774,2021-09-15 18:01:55.403,test
1451,2021-09-01 01:00:00+00:00,1001,0.126513,0.201882,583,2021-09-15 18:01:55.403,test
729,2021-09-01 01:00:00+00:00,1003,0.972299,0.071615,320,2021-09-15 18:01:55.403,test
7,2021-09-01 01:00:00+00:00,1005,0.322674,0.351670,571,2021-09-15 18:01:55.403,test
368,2021-09-01 01:00:00+00:00,1004,0.706875,0.014739,777,2021-09-15 18:01:55.403,test
1090,2021-09-01 01:00:00+00:00,1002,0.198332,0.724919,42,2021-09-15 18:01:55.403,test
1091,2021-09-01 02:00:00+00:00,1002,0.324382,0.997275,783,2021-09-15 18:01:55.403,test
730,2021-09-01 02:00:00+00:00,1003,0.447430,0.994809,222,2021-09-15 18:01:55.403,test
8,2021-09-01 02:00:00+00:00,1005,0.834001,0.414044,808,2021-09-15 18:01:55.403,test
369,2021-09-01 02:00:00+00:00,1004,0.096068,0.060952,221,2021-09-15 18:01:55.403,test
1452,2021-09-01 02:00:00+00:00,1001,0.821713,0.827314,22,2021-09-15 18:01:55.403,test

In [4]:
# Inspecting the last 50 feature rows
data.tail(50)

,event_timestamp,driver_id,conv_rate,acc_rate,avg_daily_trips,created,string_feature
1794,2021-09-15 08:00:00+00:00,1001,0.071063,0.705720,378,2021-09-15 18:01:55.403,test
1433,2021-09-15 08:00:00+00:00,1002,0.280594,0.560058,752,2021-09-15 18:01:55.403,test
350,2021-09-15 08:00:00+00:00,1005,0.104060,0.858310,617,2021-09-15 18:01:55.403,test
1072,2021-09-15 08:00:00+00:00,1003,0.546695,0.575036,821,2021-09-15 18:01:55.403,test
711,2021-09-15 08:00:00+00:00,1004,0.679559,0.896867,199,2021-09-15 18:01:55.403,test
1073,2021-09-15 09:00:00+00:00,1003,0.332432,0.749517,297,2021-09-15 18:01:55.403,test
1795,2021-09-15 09:00:00+00:00,1001,0.092437,0.442450,146,2021-09-15 18:01:55.403,test
1434,2021-09-15 09:00:00+00:00,1002,0.332864,0.183038,545,2021-09-15 18:01:55.403,test
712,2021-09-15 09:00:00+00:00,1004,0.869990,0.004725,762,2021-09-15 18:01:55.403,test
351,2021-09-15 09:00:00+00:00,1005,0.942356,0.027751,239,2021-09-15 18:01:55.403,test
713,2021-09-15 10:00:00+00:00,1004,0.179314,0.888487,129,2021-09-15 18:01:55.403,test
1796,2021-09-15 10:00:00+00:00,1001,0.224734,0.849076,450,2021-09-15 18:01:55.403,test
1435,2021-09-15 10:00:00+00:00,1002,0.904202,0.584617,607,2021-09-15 18:01:55.403,test
352,2021-09-15 10:00:00+00:00,1005,0.864282,0.806959,722,2021-09-15 18:01:55.403,test
1074,2021-09-15 10:00:00+00:00,1003,0.837609,0.963608,381,2021-09-15 18:01:55.403,test
1797,2021-09-15 11:00:00+00:00,1001,0.421481,0.678873,809,2021-09-15 18:01:55.403,test
1436,2021-09-15 11:00:00+00:00,1002,0.079039,0.073426,34,2021-09-15 18:01:55.403,test
1075,2021-09-15 11:00:00+00:00,1003,0.059882,0.317795,892,2021-09-15 18:01:55.403,test
714,2021-09-15 11:00:00+00:00,1004,0.684020,0.335085,373,2021-09-15 18:01:55.403,test
353,2021-09-15 11:00:00+00:00,1005,0.928889,0.327992,68,2021-09-15 18:01:55.403,test
1437,2021-09-15 12:00:00+00:00,1002,0.035107,0.566663,141,2021-09-15 18:01:55.403,test
715,2021-09-15 12:00:00+00:00,1004,0.538651,0.729288,519,2021-09-15 18:01:55.403,test
1076,2021-09-15 12:00:00+00:00,1003,0.388767,0.347770,9,2021-09-15 18:01:55.403,test
1798,2021-09-15 12:00:00+00:00,1001,0.480793,0.317969,103,2021-09-15 18:01:55.403,test
354,2021-09-15 12:00:00+00:00,1005,0.807436,0.067369,936,2021-09-15 18:01:55.403,test
1438,2021-09-15 13:00:00+00:00,1002,0.187022,0.636303,698,2021-09-15 18:01:55.403,test
1799,2021-09-15 13:00:00+00:00,1001,0.217096,0.161140,800,2021-09-15 18:01:55.403,test
355,2021-09-15 13:00:00+00:00,1005,0.109662,0.948472,863,2021-09-15 18:01:55.403,test
1077,2021-09-15 13:00:00+00:00,1003,0.874185,0.446985,255,2021-09-15 18:01:55.403,test
716,2021-09-15 13:00:00+00:00,1004,0.692943,0.251203,289,2021-09-15 18:01:55.403,test
1078,2021-09-15 14:00:00+00:00,1003,0.580215,0.259824,379,2021-09-15 18:01:55.403,test
717,2021-09-15 14:00:00+00:00,1004,0.285921,0.871101,582,2021-09-15 18:01:55.403,test
1439,2021-09-15 14:00:00+00:00,1002,0.481214,0.767431,55,2021-09-15 18:01:55.403,test
1800,2021-09-15 14:00:00+00:00,1001,0.778216,0.069670,151,2021-09-15 18:01:55.403,test
356,2021-09-15 14:00:00+00:00,1005,0.287409,0.477578,354,2021-09-15 18:01:55.403,test
1440,2021-09-15 15:00:00+00:00,1002,0.726674,0.019728,737,2021-09-15 18:01:55.403,test
1801,2021-09-15 15:00:00+00:00,1001,0.293925,0.148313,716,2021-09-15 18:01:55.403,test
357,2021-09-15 15:00:00+00:00,1005,0.460150,0.349922,557,2021-09-15 18:01:55.403,test
1079,2021-09-15 15:00:00+00:00,1003,0.404311,0.176628,194,2021-09-15 18:01:55.403,test
718,2021-09-15 15:00:00+00:00,1004,0.254299,0.275834,293,2021-09-15 18:01:55.403,test
1802,2021-09-15 16:00:00+00:00,1001,0.681178,0.449826,906,2021-09-15 18:01:55.403,test
1441,2021-09-15 16:00:00+00:00,1002,0.516491,0.795655,594,2021-09-15 18:01:55.403,test
358,2021-09-15 16:00:00+00:00,1005,0.072890,0.136999,154,2021-09-15 18:01:55.403,test
1080,2021-09-15 16:00:00+00:00,1003,0.501248,0.094142,435,2021-09-15 18:01:55.403,test
719,2021-09-15 16:00:00+00:00,1004,0.986123,0.601093,951,2021-09-15 18:01:55.403,test
720,2021-09-15 17:00:00+00:00,1004,0.541801,0.595369,539,2021-09-15 18:01:55.403,test
359,2021-09-15 17:00:00+00:00,1005,0.318631,0.527131,189,2021-09-15 18:01:55.403,test
1442,2021-09-15 17:00:00+00:00,1002,0.379485,0.151377,315,2021-09-15 18:01:55.403,test
1803,2021-09-15 17:00:00+00:00,1001,0.812357,0.840873,714,2021-09-15 18:01:55.403,test
1081,2021-09-15 17:00:00+00:00,1003,0.072028,0.032925,41,2021-09-15 18:01:55.403,test

In [12]:
# Getting the list of unique driver IDs
print(f"Unique driver IDs are {np.array2string(data['driver_id'].unique())}")

Unique driver IDs are [1003 1004 1002 1005 1001]

In [14]:
df2 = data
df2.sort_values(["driver_id", "event_timestamp"], inplace=True)
df2["diffs"] = df2.groupby(["driver_id"])["event_timestamp"].transform(lambda x: x.diff())

In [15]:
df2["diffs"].head()

1804                 NaT
1444   141 days 11:00:00
1445     0 days 01:00:00
1446     0 days 01:00:00
1447     0 days 01:00:00
Name: diffs, dtype: timedelta64[ns]

In [26]:
# Checking which indices the time difference is different than one hour
for i in range(len(df2["diffs"])):
    if df2.iloc[i]["diffs"] != pd.Timedelta("0 days 01:00:00"):
        print(f"Timedelta is not one hour for index {i} and its previous index")

Timedelta is not one hour for index 0 and its previous index
Timedelta is not one hour for index 1 and its previous index
Timedelta is not one hour for index 361 and its previous index
Timedelta is not one hour for index 362 and its previous index
Timedelta is not one hour for index 722 and its previous index
Timedelta is not one hour for index 723 and its previous index
Timedelta is not one hour for index 904 and its previous index
Timedelta is not one hour for index 905 and its previous index
Timedelta is not one hour for index 1085 and its previous index
Timedelta is not one hour for index 1086 and its previous index
Timedelta is not one hour for index 1446 and its previous index
Timedelta is not one hour for index 1447 and its previous index

In [27]:
# Difference is not one hour at index 0 because there are no indices before 0
# Difference is not one hour at index 1 because timestamps jump from 2021-04-12 to 2021-08-31
df2[:2]

,event_timestamp,driver_id,conv_rate,acc_rate,avg_daily_trips,created,string_feature,diffs
1804,2021-04-12 07:00:00+00:00,1001,0.701558,0.195824,566,2021-09-15 18:01:55.403,test,NaT
1444,2021-08-31 18:00:00+00:00,1001,0.910018,0.580611,666,2021-09-15 18:01:55.403,test,141 days 11:00:00

In [29]:
# Difference is not one hour at index 361 because previous index is for a different ID
# Difference is not one hour at index 362 because timestamps jump from 2021-04-12 to 2021-08-31
df2[360:363]

,event_timestamp,driver_id,conv_rate,acc_rate,avg_daily_trips,created,string_feature,diffs
1803,2021-09-15 17:00:00+00:00,1001,0.812357,0.840873,714,2021-09-15 18:01:55.403,test,0 days 01:00:00
1443,2021-04-12 07:00:00+00:00,1002,0.775499,0.947109,890,2021-09-15 18:01:55.403,test,NaT
1083,2021-08-31 18:00:00+00:00,1002,0.381206,0.347303,268,2021-09-15 18:01:55.403,test,141 days 11:00:00

In [ ]:
# Difference is not one hour at index 722 because previous index is for a different ID
# Difference is not one hour at index 723 because timestamps jump from 2021-04-12 to 2021-08-31
df2[721:724]

In [31]:
# Difference is not one hour at index 904 and 905 because they are duplicates of index 903
df2[903:906]

,event_timestamp,driver_id,conv_rate,acc_rate,avg_daily_trips,created,string_feature,diffs
1806,2021-09-08 06:00:00+00:00,1003,0.084715,0.615489,523,2021-09-15 18:01:55.403,test,0 days 01:00:00
1805,2021-09-08 06:00:00+00:00,1003,0.084715,0.615489,523,2021-09-15 18:01:55.403,test,0 days 00:00:00
902,2021-09-08 06:00:00+00:00,1003,0.084715,0.615489,523,2021-09-15 18:01:55.403,test,0 days 00:00:00

In [32]:
# Difference is not one hour at index 1085 because previous index is for a different ID
# Difference is not one hour at index 1086 because timestamps jump from 2021-04-12 to 2021-08-31
df2[1084:1087]

,event_timestamp,driver_id,conv_rate,acc_rate,avg_daily_trips,created,string_feature,diffs
1081,2021-09-15 17:00:00+00:00,1003,0.072028,0.032925,41,2021-09-15 18:01:55.403,test,0 days 01:00:00
721,2021-04-12 07:00:00+00:00,1004,0.891017,0.118256,154,2021-09-15 18:01:55.403,test,NaT
361,2021-08-31 18:00:00+00:00,1004,0.527224,0.893340,963,2021-09-15 18:01:55.403,test,141 days 11:00:00

In [35]:
# Difference is not one hour at index 1446 because previous index is for a different ID
# Difference is not one hour at index 1447 because timestamps jump from 2021-04-12 to 2021-08-31
df2.iloc[1445:1448]

,event_timestamp,driver_id,conv_rate,acc_rate,avg_daily_trips,created,string_feature,diffs
720,2021-09-15 17:00:00+00:00,1004,0.541801,0.595369,539,2021-09-15 18:01:55.403,test,0 days 01:00:00
360,2021-04-12 07:00:00+00:00,1005,0.138263,0.955520,553,2021-09-15 18:01:55.403,test,NaT
0,2021-08-31 18:00:00+00:00,1005,0.362754,0.697629,31,2021-09-15 18:01:55.403,test,141 days 11:00:00